### ISSUE TITLE
Towards v3.0

### ISSUE THREAD

**Issue by dkarrasch** [Jutho/LinearMaps.jl#101]
We have currently two PRs in the pipeline that are breaking and therefore require a major release. So I thought we should collect ideas on what to put in there to not have major release every month or so. Clearly, we will have

- [x] #100 

- [x] #97 

Furthermore, I'd suggest to include
- [x] #87 with the new show methods (I guess the only way to really get a feeling for whether it's good or not is to start using it and collect "annoyed" feedback, otherwise I feel this is too distant to form an opinion just by reviewing the PR)
- [x] a nice Documenter documentation, which then could nicely address #98 (That shouldn't be too hard: I'm planning to mainly cut our long README into more digestible pieces as a first approach.)

Anything else? Of course, if some hot PR comes in, there's nothing that stops us from merging it and releasing another v2.x. I'd hope to finish this some time in late August/early September. Any contributions/PRs/suggestions are more than welcome.

Have a good (rest of the) summer everyone!

EDIT:
- [x] I think we should relax the type of the output variable in the `mul!`s to `AbstractVecOrMat`. The following works perfectly fine with matrices in `LinearAlgebra`:
```
using LinearAlgebra
mul!(rand(5,1), rand(5,5), rand(5))
```

TODO:
- [x] overhaul by @Jutho 
- [x] document how to write custom map types #111 
- [ ] ~~document conversion logic~~ (not sure that's of general interest)
- [x] `FillMap`s

**Comment by Jutho** [comment]
All for this proposal, I will also try to find some time to review current PRs, and contribute where possible.

**Comment by dkarrasch** [comment]
Gentle bump. What remains to be done is to decide if we want the constructor `LinearMap(::Number, m, n)` for `FillMap`s (or whether this is too close to `UniformScaling`-like maps) and a potential overhaul. I should add that the package is now basically 100% tested, so we might have a performance-oriented overhaul after we release v3.0.
